name: portainer-agent
version: '2.33.1'
base: core22
summary: Portainer Edge Agent
description: |
 This snap contains the Portainer Edge Agent docker image.
 The agent will automatically connect to Portainer Edge Management.

grade: stable
confinement: strict

architectures:
  - build-on: [amd64,arm64]
    build-for: [amd64]
  - build-on: [amd64,arm64]
    build-for: [arm64]

parts:
 docker-compose:
   plugin: dump
   source: ./docker-compose
   organize:
     '*': docker-compose/${SNAPCRAFT_PROJECT_NAME}/
 configs:
   source: ./configs
   plugin: dump
   organize:
     'package-assets/*': package-assets/${SNAPCRAFT_PROJECT_NAME}/

slots:
 docker-compose:
   interface: content
   content: docker-compose
   source:
     read:
       - $SNAP/docker-compose/${SNAPCRAFT_PROJECT_NAME}
 docker-volumes:
   interface: content
   content: docker-volumes
   source:
     write:
       - $SNAP_DATA/docker-volumes/${SNAPCRAFT_PROJECT_NAME}
 package-assets:
   interface: content
   content: package-assets
   source:
     read:
       - $SNAP/package-assets/${SNAPCRAFT_PROJECT_NAME}
 package-run:
   interface: content
   content: package-run
   source:
     write:
       - $SNAP_DATA/package-run/${SNAPCRAFT_PROJECT_NAME}     
